## Question 3
The data shown in the figure below shows data generated from two processes. The data generating processes are multivariate normal distributions with parameters
* Class A (red): mean $\bar{\mathbf{x}}_\mathrm{A}= \begin{pmatrix}5.0\\3.0\end{pmatrix}$; covariance $\mathbf{\Sigma}_\mathrm{A}=\begin{pmatrix}1.26 & -1.51\\ -1.51 & 3.26\end{pmatrix}$
* Class B (green): mean $\bar{\mathbf{x}}_\mathrm{A}= \begin{pmatrix}-4.0\\-4.0\end{pmatrix}$; covariance $\mathbf{\Sigma}_\mathrm{A}=\begin{pmatrix}6.22 & 0.09\\ 0.09 & 2.91\end{pmatrix}$

The decision rule for quadratic discrimination analyis is given by
\[\mbox{if}\,Q(\bx)>0\,\mbox{assign $\bx$ to class A}\]
where 
* $Q(\mathbf{x}) = \mathbf{x}^\mathrm{T}\mathbf{A}\mathbf{x} + \mathbf{b}^\mathrm{T}\mathbf{x} + c$
* $\mathbf{A} = -\frac{1}{2}\left(\mathbf{\Sigma}_\mathrm{A}^{-1}-\mathbf{\Sigma}_\mathrm{B}^{-1}\right)$
* $\mathbf{b} = \mathbf{\Sigma}^{-1}_\mathrm{A}\bar{\mathbf{x}}_\mathrm{A} - \mathbf{\Sigma}^{-1}_\mathrm{B}\bar{\mathbf{x}}_\mathrm{B}$
* $c = -\frac{1}{2}\left(\log_e\frac{ \left\lvert \mathbf{\Sigma}_\mathrm{A} \right\rvert }{ \left\lvert \mathbf{\Sigma}_\mathrm{B} \right\rvert }+\bar{\mathbf{x}}_\mathrm{A}^\mathrm{T}\mathbf{\Sigma}_\mathrm{A}^{-1}\bar{\mathbf{x}}_\mathrm{A}-\bar{\mathbf{x}}_\mathrm{B}^\mathrm{T}\mathbf{\Sigma}_\mathrm{B}^{-1}\bar{\mathbf{x}}_\mathrm{B}\right)-\log_e\frac{\pi_\mathrm{A}}{\pi_\mathrm{B}}$


The relevant quantities are defined or computed in the following cell:

In [1]:
import numpy as np

# Define the means
meanA = np.array([5.0, 3.0])
meanB = np.array([-4.0, -4.0])

# Covariances
covA = np.array([[1.26, -1.51], [-1.51, 3.26]])
covB = np.array([[6.22, 0.09], [0.09, 2.91]])

# Priors
pA = 0.5
pB = 1 - pA

# Define the decision rule
icovA = np.linalg.inv(covA)
icovB = np.linalg.inv(covB)
A = -0.5 * (icovA - icovB)
b = np.matmul(icovA, meanA.T) - np.matmul(icovB, meanB.T)

# IMPORTANT: THE THIRD LINE OF THIS EXPRESSION HAS THE WRONG SIGN. + SHOULD BE -.
c = -0.5 * (np.log(np.linalg.det(covA)/np.linalg.det(covB))
            + np.matmul(meanA,np.matmul(icovA, meanA.T))
            + np.matmul(meanB,np.matmul(icovB, meanB.T))
            ) - np.log(pA/pB)
           

# Given point x, compute the decision function
Q = lambda x: np.matmul(x, np.matmul(A, x.T)) + np.matmul(b.T, x) + c

Example of how to use the decision function $Q(x)$:

Define five random points in the range $x_0:(-15,15)$, $x_1: (10,10)$

In [2]:
X = np.random.rand(5,2)
X[:,0] = X[:,0]*30 - 15
X[:,1] = X[:,1]*20 - 10
print(X)

[[-10.74731844   8.94898223]
 [-11.00445487  -8.38876056]
 [-14.34034101  -5.84025932]
 [ -7.66316086   3.7030207 ]
 [  7.11801655   4.52801977]]


Apply the decision function to all the points

In [3]:
Qx = np.array([ Q(x) for x in X ])

Classify the points. We assume that none are exactly on the boundary.

In [4]:
cA = X[Qx>0,:]
cB = X[Qx<0,:]
print('Points in class A')
print(cA)
print('Points in class B')
print(cB)

Points in class A
[[7.11801655 4.52801977]]
Points in class B
[[-10.74731844   8.94898223]
 [-11.00445487  -8.38876056]
 [-14.34034101  -5.84025932]
 [ -7.66316086   3.7030207 ]]
