In [2]:
from __future__ import print_function
import torch

In [3]:
import torch
torch.cuda.is_available()

True

### Tensor

In [4]:
# Unintialised
x = torch.empty(5, 3)
x

tensor([[2.5226e-18, 1.6898e-04, 1.0072e-11],
        [7.7201e-10, 1.0564e-05, 4.1656e-11],
        [1.7156e-07, 2.9572e-18, 6.7333e+22],
        [1.7591e+22, 1.7184e+25, 4.3222e+27],
        [6.1972e-04, 7.2443e+22, 1.7728e+28]])

In [5]:
# Randomly initialised
x = torch.rand(5, 3)
x

tensor([[0.1616, 0.5189, 0.8957],
        [0.4782, 0.7047, 0.3290],
        [0.3798, 0.2065, 0.1260],
        [0.3411, 0.0244, 0.6938],
        [0.0586, 0.5345, 0.6200]])

In [6]:
# Zero matrix
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
# Construct from data
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

#### create a tensor based on an existing tensor: <br/>
These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                               

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2993,  1.1857,  1.1707],
        [-0.9193, -0.3698,  0.6986],
        [ 0.0283, -0.9884,  1.7813],
        [ 0.0886, -0.9493, -0.4911],
        [ 0.2103, -0.4377,  0.0700]])


In [11]:
# Get tensor size
print(x.size())

torch.Size([5, 3])


### Operations

In [12]:
# Addition
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

tensor([[ 1.2934e+00,  1.7855e+00,  1.9932e+00],
        [-8.3368e-01, -1.4997e-03,  1.3006e+00],
        [ 4.3439e-01, -7.2240e-01,  2.5838e+00],
        [ 1.6056e-01, -6.6759e-01,  4.7991e-01],
        [ 9.4833e-01,  5.1749e-01,  7.4557e-01]])
tensor([[ 1.2934e+00,  1.7855e+00,  1.9932e+00],
        [-8.3368e-01, -1.4997e-03,  1.3006e+00],
        [ 4.3439e-01, -7.2240e-01,  2.5838e+00],
        [ 1.6056e-01, -6.6759e-01,  4.7991e-01],
        [ 9.4833e-01,  5.1749e-01,  7.4557e-01]])


In [13]:
# Addition to an output
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2934e+00,  1.7855e+00,  1.9932e+00],
        [-8.3368e-01, -1.4997e-03,  1.3006e+00],
        [ 4.3439e-01, -7.2240e-01,  2.5838e+00],
        [ 1.6056e-01, -6.6759e-01,  4.7991e-01],
        [ 9.4833e-01,  5.1749e-01,  7.4557e-01]])


In [14]:
# Addition in-place
y.add_(x)
y

tensor([[ 1.2934e+00,  1.7855e+00,  1.9932e+00],
        [-8.3368e-01, -1.4997e-03,  1.3006e+00],
        [ 4.3439e-01, -7.2240e-01,  2.5838e+00],
        [ 1.6056e-01, -6.6759e-01,  4.7991e-01],
        [ 9.4833e-01,  5.1749e-01,  7.4557e-01]])

#### * Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [16]:
# Numpy indexing
print(x[:, 1])

tensor([ 1.1857, -0.3698, -0.9884, -0.9493, -0.4377])


In [17]:
# Resizing
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
# Get the value in one element tensors as a scalar 
x = torch.randn(1)
print(x.item())

-0.8435218334197998


### Numpy Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [27]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [32]:
gpu = torch.device("cuda")  # a CUDA device object
y = torch.ones_like(x, device=gpu)  # directly create a tensor on GPU
x = x.to(device)    # or just use strings ``.to("cuda")``

z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([0.1565], device='cuda:0')
tensor([0.1565], dtype=torch.float64)
