In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

### Tensor

In [3]:
# Unintialised
x = torch.empty(5, 3)
x

tensor([[ 0.0000e+00,  8.5899e+09,  4.9098e+14],
        [-1.5849e+29,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
# Randomly initialised
x = torch.rand(5, 3)
x

tensor([[0.5129, 0.0531, 0.2512],
        [0.2420, 0.5536, 0.3207],
        [0.5416, 0.7206, 0.1616],
        [0.8440, 0.7458, 0.1861],
        [0.2472, 0.9341, 0.6818]])

In [5]:
# Zero matrix
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
# Construct from data
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

#### create a tensor based on an existing tensor: <br/>
These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                               

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.5472, -0.1285, -0.1210],
        [ 0.0579, -0.9598,  0.9002],
        [-1.2212,  0.8247, -1.3845],
        [-1.0608,  0.9557, -0.7146],
        [-0.1315,  0.7575,  0.2761]])


In [8]:
# Get tensor size
print(x.size())

torch.Size([5, 3])


### Operations

In [9]:
# Addition
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

tensor([[-0.9321,  0.6717,  0.3389],
        [ 0.3964, -0.8721,  1.8867],
        [-0.4621,  1.6593, -1.1908],
        [-0.2980,  1.5438,  0.2225],
        [ 0.7244,  1.1888,  1.1450]])
tensor([[-0.9321,  0.6717,  0.3389],
        [ 0.3964, -0.8721,  1.8867],
        [-0.4621,  1.6593, -1.1908],
        [-0.2980,  1.5438,  0.2225],
        [ 0.7244,  1.1888,  1.1450]])


In [10]:
# Addition to an output
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9321,  0.6717,  0.3389],
        [ 0.3964, -0.8721,  1.8867],
        [-0.4621,  1.6593, -1.1908],
        [-0.2980,  1.5438,  0.2225],
        [ 0.7244,  1.1888,  1.1450]])


In [11]:
# Addition in-place
y.add_(x)
y

tensor([[-0.9321,  0.6717,  0.3389],
        [ 0.3964, -0.8721,  1.8867],
        [-0.4621,  1.6593, -1.1908],
        [-0.2980,  1.5438,  0.2225],
        [ 0.7244,  1.1888,  1.1450]])

#### * Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [12]:
# Numpy indexing
print(x[:, 1])

tensor([-0.1285, -0.9598,  0.8247,  0.9557,  0.7575])


In [13]:
# Resizing
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# Get the value in one element tensors as a scalar 
x = torch.randn(1)
print(x.item())

1.6542985439300537


### Numpy Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [15]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [18]:
gpu = torch.device("cuda")  # a CUDA device object
y = torch.ones_like(x, device=gpu)  # directly create a tensor on GPU
x = x.to(gpu)    # or just use strings ``.to("cuda")``

z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([2.6543], device='cuda:0')
tensor([2.6543], dtype=torch.float64)
