In [12]:
import numpy as np

### Q1

In [1]:
from sklearn import tree

C:\Users\just4\Miniconda3\envs\ml\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [24]:
train_set = np.array([[0,0,0],[0,0,1],[0,1,0],[1,0,1],[1,1,0],[1,1,1]])
train_label = np.array([0,0,0,1,0,1])

In [27]:
DT = tree.DecisionTreeClassifier(criterion='entropy')
model = DT.fit(train_set, train_label)

In [29]:
model.predict([[0,1,1], [1,0,0]])

array([0, 0])

### Q2

In [36]:
import pandas as pd

In [43]:
test_data = pd.read_csv('C:/Users/just4/OneDrive/ACS/Machine_Learning/Lab/assignment4-q3.csv')
test_data

-6.600440533056271875e+00  7.538687788376366994e-01  \
0                     -3.654231                  0.325552   
1                     -0.647433                 -5.374509   
2                      0.250021                  3.428828   
3                      5.401426                 -0.217909   
4                      0.649667                  5.842321   
...                         ...                       ...   
9994                  -0.267487                 -5.707709   
9995                   0.137246                  5.698536   
9996                   0.495448                 -6.344917   
9997                  -4.004405                  0.157959   
9998                  -4.425379                  0.786903   

      -2.468157769410755376e-01  6.878833252597749137e-02  \
0                     -0.269918                 -0.876327   
1                      0.444086                  0.864371   
2                     -0.403042                 -4.269514   
3                      0.606282                  0.864640   
4                      0.642524                 -4.894259   
...                         ...                       ...   
9994                   1.520693                  0.317077   
9995                   0.756645                 -5.568357   
9996                  -0.844630                 -0.451231   
9997                   0.834499                 -0.943384   
9998                   0.273073                  1.310924   

      3.225767379972037663e-01  
0                    -1.425211  
1                     5.073218  
2                    -0.469498  
3                    -3.294026  
4                     0.701021  
...                        ...  
9994                  5.903460  
9995                  1.546414  
9996                  5.497714  
9997                 -0.067830  
9998                 -0.068100  

[9999 rows x 5 columns]

In [59]:
from sklearn.cluster import KMeans
km = KMeans(5).fit(test_data)

In [62]:
np.unique(km.labels_, return_counts=True)

(array([0, 1, 2, 3, 4]), array([2000, 2006, 2000, 1999, 1994], dtype=int64))

In [63]:
km.cluster_centers_

array([[ 5.02923153e+00,  3.20977961e-02, -3.55040211e-03,
        -3.27914208e-02, -4.96644978e+00],
       [-8.47841228e-03, -5.00203202e+00,  3.15907356e-02,
        -4.20789150e-03,  5.02588324e+00],
       [-2.72900657e-03,  5.01611084e+00, -1.44366549e-02,
        -5.00974530e+00,  9.64629268e-03],
       [-4.97948980e+00,  3.27573747e-02, -1.96358816e-02,
         8.72354183e-03,  6.57970524e-03],
       [-9.29328718e-03, -4.97572105e+00, -1.28653231e-02,
        -5.01817301e+00,  5.00746739e+00]])

In [ ]:
0,-5,0,-5,5