Quiz 1

In [1]:
import numpy as np

In [5]:
x = np.array([1.2, 2.4, 3.1, 3.9, 5.2])
x

array([1.2, 2.4, 3.1, 3.9, 5.2])

In [6]:
y = np.array([-1.47, 1.73, 4.52, 7.03, 10.33])
y

array([-1.47,  1.73,  4.52,  7.03, 10.33])

In [20]:
m = 2.96
c = -5.01

In [21]:
f = m*x + c
f

array([-1.458,  2.094,  4.166,  6.534, 10.382])

In [22]:
LSE = sum((f-y)**2)
LSE

0.5066759999999991

In [19]:
LSE = sum((f-y)**2)
LSE

3.580500000000005